name: communitils docs site deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main]
    paths: [site/**]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ðŸ”Ž
        uses: actions/checkout@v4
      - name: Install Vercel CLI ðŸ“¦
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information ðŸ“„
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts ðŸ”§
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel ðŸš¢
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
